insert into app_category (id, name) values (1, 'Exterior Signage');
insert into app_category (id, name) values (2, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (3, 'Landscaping & Irrigation');
insert into app_category (id, name) values (4, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (5, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (6, 'Drilled Shafts');
insert into app_category (id, name) values (7, 'Framing (Steel)');
insert into app_category (id, name) values (8, 'Roofing (Metal)');
insert into app_category (id, name) values (9, 'Electrical');
insert into app_category (id, name) values (10, 'Fire Protection');
insert into app_category (id, name) values (11, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (12, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (13, 'Asphalt Paving');
insert into app_category (id, name) values (14, 'HVAC');
insert into app_category (id, name) values (15, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (16, 'Framing (Steel)');
insert into app_category (id, name) values (17, 'Prefabricated Aluminum Metal Canopies');
insert into app_category (id, name) values (18, 'EIFS');
insert into app_category (id, name) values (19, 'Exterior Signage');
insert into app_category (id, name) values (20, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (21, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (22, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (23, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (24, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (25, 'Masonry & Precast');
insert into app_category (id, name) values (26, 'Ornamental Railings');
insert into app_category (id, name) values (27, 'HVAC');
insert into app_category (id, name) values (28, 'Elevator');
insert into app_category (id, name) values (29, 'RF Shielding');
insert into app_category (id, name) values (30, 'Electrical');
insert into app_category (id, name) values (31, 'RF Shielding');
insert into app_category (id, name) values (32, 'Overhead Doors');
insert into app_category (id, name) values (33, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (34, 'Curb & Gutter');
insert into app_category (id, name) values (35, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (36, 'Casework');
insert into app_category (id, name) values (37, 'Roofing (Metal)');
insert into app_category (id, name) values (38, 'Wall Protection');
insert into app_category (id, name) values (39, 'Fire Protection');
insert into app_category (id, name) values (40, 'Fire Sprinkler System');
insert into app_category (id, name) values (41, 'Fire Sprinkler System');
insert into app_category (id, name) values (42, 'Overhead Doors');
insert into app_category (id, name) values (43, 'HVAC');
insert into app_category (id, name) values (44, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (45, 'Exterior Signage');
insert into app_category (id, name) values (46, 'HVAC');
insert into app_category (id, name) values (47, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (48, 'EIFS');
insert into app_category (id, name) values (49, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (50, 'HVAC');
insert into app_category (id, name) values (51, 'Ornamental Railings');
insert into app_category (id, name) values (52, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (53, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (54, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (55, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (56, 'Granite Surfaces');
insert into app_category (id, name) values (57, 'RF Shielding');
insert into app_category (id, name) values (58, 'Wall Protection');
insert into app_category (id, name) values (59, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (60, 'Termite Control');
insert into app_category (id, name) values (61, 'Prefabricated Aluminum Metal Canopies');
insert into app_category (id, name) values (62, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (63, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (64, 'Fire Sprinkler System');
insert into app_category (id, name) values (65, 'Hard Tile & Stone');
insert into app_category (id, name) values (66, 'Roofing (Metal)');
insert into app_category (id, name) values (67, 'Site Furnishings');
insert into app_category (id, name) values (68, 'Masonry & Precast');
insert into app_category (id, name) values (69, 'Fire Protection');
insert into app_category (id, name) values (70, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (71, 'Casework');
insert into app_category (id, name) values (72, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (73, 'Marlite Panels (FED)');
insert into app_category (id, name) values (74, 'Sitework & Site Utilities');
insert into app_category (id, name) values (75, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (76, 'Wall Protection');
insert into app_category (id, name) values (77, 'Fire Sprinkler System');
insert into app_category (id, name) values (78, 'Waterproofing & Caulking');
insert into app_category (id, name) values (79, 'Elevator');
insert into app_category (id, name) values (80, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (81, 'Granite Surfaces');
insert into app_category (id, name) values (82, 'Framing (Wood)');
insert into app_category (id, name) values (83, 'Fire Sprinkler System');
insert into app_category (id, name) values (84, 'Sitework & Site Utilities');
insert into app_category (id, name) values (85, 'Masonry');
insert into app_category (id, name) values (86, 'Wall Protection');
insert into app_category (id, name) values (87, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (88, 'Marlite Panels (FED)');
insert into app_category (id, name) values (89, 'HVAC');
insert into app_category (id, name) values (90, 'Overhead Doors');
insert into app_category (id, name) values (91, 'Fire Protection');
insert into app_category (id, name) values (92, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (93, 'Overhead Doors');
insert into app_category (id, name) values (94, 'Drilled Shafts');
insert into app_category (id, name) values (95, 'Fire Sprinkler System');
insert into app_category (id, name) values (96, 'Elevator');
insert into app_category (id, name) values (97, 'Wall Protection');
insert into app_category (id, name) values (98, 'Fire Protection');
insert into app_category (id, name) values (99, 'Exterior Signage');
insert into app_category (id, name) values (100, 'Granite Surfaces');
insert into app_category (id, name) values (101, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (102, 'Granite Surfaces');
insert into app_category (id, name) values (103, 'Ornamental Railings');
insert into app_category (id, name) values (104, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (105, 'Curb & Gutter');
insert into app_category (id, name) values (106, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (107, 'Framing (Steel)');
insert into app_category (id, name) values (108, 'Fire Protection');
insert into app_category (id, name) values (109, 'Epoxy Flooring');
insert into app_category (id, name) values (110, 'Elevator');
insert into app_category (id, name) values (111, 'Sitework & Site Utilities');
insert into app_category (id, name) values (112, 'Framing (Wood)');
insert into app_category (id, name) values (113, 'Prefabricated Aluminum Metal Canopies');
insert into app_category (id, name) values (114, 'Granite Surfaces');
insert into app_category (id, name) values (115, 'EIFS');
insert into app_category (id, name) values (116, 'Ornamental Railings');
insert into app_category (id, name) values (117, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (118, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (119, 'Exterior Signage');
insert into app_category (id, name) values (120, 'Curb & Gutter');
insert into app_category (id, name) values (121, 'Hard Tile & Stone');
insert into app_category (id, name) values (122, 'Curb & Gutter');
insert into app_category (id, name) values (123, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (124, 'Soft Flooring and Base');
insert into app_category (id, name) values (125, 'Masonry & Precast');
insert into app_category (id, name) values (126, 'Elevator');
insert into app_category (id, name) values (127, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (128, 'HVAC');
insert into app_category (id, name) values (129, 'Electrical');
insert into app_category (id, name) values (130, 'Masonry & Precast');
insert into app_category (id, name) values (131, 'Granite Surfaces');
insert into app_category (id, name) values (132, 'HVAC');
insert into app_category (id, name) values (133, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (134, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (135, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (136, 'Sitework & Site Utilities');
insert into app_category (id, name) values (137, 'Roofing (Asphalt)');
insert into app_category (id, name) values (138, 'Framing (Steel)');
insert into app_category (id, name) values (139, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (140, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (141, 'Curb & Gutter');
insert into app_category (id, name) values (142, 'Granite Surfaces');
insert into app_category (id, name) values (143, 'Framing (Steel)');
insert into app_category (id, name) values (144, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (145, 'Roofing (Metal)');
insert into app_category (id, name) values (146, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (147, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (148, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (149, 'Roofing (Asphalt)');
insert into app_category (id, name) values (150, 'Drilled Shafts');
insert into app_category (id, name) values (151, 'Framing (Steel)');
insert into app_category (id, name) values (152, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (153, 'Site Furnishings');
insert into app_category (id, name) values (154, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (155, 'Prefabricated Aluminum Metal Canopies');
insert into app_category (id, name) values (156, 'Exterior Signage');
insert into app_category (id, name) values (157, 'Marlite Panels (FED)');
insert into app_category (id, name) values (158, 'Overhead Doors');
insert into app_category (id, name) values (159, 'Sitework & Site Utilities');
insert into app_category (id, name) values (160, 'Glass & Glazing');
insert into app_category (id, name) values (161, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (162, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (163, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (164, 'Asphalt Paving');
insert into app_category (id, name) values (165, 'Casework');
insert into app_category (id, name) values (166, 'EIFS');
insert into app_category (id, name) values (167, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (168, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (169, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (170, 'Granite Surfaces');
insert into app_category (id, name) values (171, 'Wall Protection');
insert into app_category (id, name) values (172, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (173, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (174, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (175, 'Marlite Panels (FED)');
insert into app_category (id, name) values (176, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (177, 'Landscaping & Irrigation');
insert into app_category (id, name) values (178, 'Glass & Glazing');
insert into app_category (id, name) values (179, 'Roofing (Asphalt)');
insert into app_category (id, name) values (180, 'HVAC');
insert into app_category (id, name) values (181, 'Drilled Shafts');
insert into app_category (id, name) values (182, 'Termite Control');
insert into app_category (id, name) values (183, 'Hard Tile & Stone');
insert into app_category (id, name) values (184, 'Drilled Shafts');
insert into app_category (id, name) values (185, 'Electrical');
insert into app_category (id, name) values (186, 'Landscaping & Irrigation');
insert into app_category (id, name) values (187, 'Drilled Shafts');
insert into app_category (id, name) values (188, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (189, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (190, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (191, 'Waterproofing & Caulking');
insert into app_category (id, name) values (192, 'Electrical');
insert into app_category (id, name) values (193, 'EIFS');
insert into app_category (id, name) values (194, 'Fire Sprinkler System');
insert into app_category (id, name) values (195, 'HVAC');
insert into app_category (id, name) values (196, 'Roofing (Metal)');
insert into app_category (id, name) values (197, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (198, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (199, 'Overhead Doors');
insert into app_category (id, name) values (200, 'Marlite Panels (FED)');
insert into app_category (id, name) values (201, 'Marlite Panels (FED)');
insert into app_category (id, name) values (202, 'Electrical');
insert into app_category (id, name) values (203, 'Masonry & Precast');
insert into app_category (id, name) values (204, 'Fire Protection');
insert into app_category (id, name) values (205, 'Masonry');
insert into app_category (id, name) values (206, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (207, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (208, 'Marlite Panels (FED)');
insert into app_category (id, name) values (209, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (210, 'Curb & Gutter');
insert into app_category (id, name) values (211, 'Overhead Doors');
insert into app_category (id, name) values (212, 'Overhead Doors');
insert into app_category (id, name) values (213, 'Ornamental Railings');
insert into app_category (id, name) values (214, 'Wall Protection');
insert into app_category (id, name) values (215, 'Roofing (Metal)');
insert into app_category (id, name) values (216, 'Casework');
insert into app_category (id, name) values (217, 'Glass & Glazing');
insert into app_category (id, name) values (218, 'Overhead Doors');
insert into app_category (id, name) values (219, 'HVAC');
insert into app_category (id, name) values (220, 'Fire Sprinkler System');
insert into app_category (id, name) values (221, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (222, 'Wall Protection');
insert into app_category (id, name) values (223, 'Framing (Steel)');
insert into app_category (id, name) values (224, 'Masonry');
insert into app_category (id, name) values (225, 'HVAC');
insert into app_category (id, name) values (226, 'Termite Control');
insert into app_category (id, name) values (227, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (228, 'Roofing (Metal)');
insert into app_category (id, name) values (229, 'Hard Tile & Stone');
insert into app_category (id, name) values (230, 'Framing (Wood)');
insert into app_category (id, name) values (231, 'Fire Sprinkler System');
insert into app_category (id, name) values (232, 'Ornamental Railings');
insert into app_category (id, name) values (233, 'Sitework & Site Utilities');
insert into app_category (id, name) values (234, 'Exterior Signage');
insert into app_category (id, name) values (235, 'Casework');
insert into app_category (id, name) values (236, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (237, 'Hard Tile & Stone');
insert into app_category (id, name) values (238, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (239, 'Roofing (Metal)');
insert into app_category (id, name) values (240, 'Framing (Wood)');
insert into app_category (id, name) values (241, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (242, 'Framing (Wood)');
insert into app_category (id, name) values (243, 'Landscaping & Irrigation');
insert into app_category (id, name) values (244, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (245, 'Framing (Wood)');
insert into app_category (id, name) values (246, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (247, 'Fire Protection');
insert into app_category (id, name) values (248, 'Epoxy Flooring');
insert into app_category (id, name) values (249, 'Epoxy Flooring');
insert into app_category (id, name) values (250, 'Exterior Signage');
insert into app_category (id, name) values (251, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (252, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (253, 'Casework');
insert into app_category (id, name) values (254, 'HVAC');
insert into app_category (id, name) values (255, 'Fire Sprinkler System');
insert into app_category (id, name) values (256, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (257, 'RF Shielding');
insert into app_category (id, name) values (258, 'Roofing (Asphalt)');
insert into app_category (id, name) values (259, 'Framing (Steel)');
insert into app_category (id, name) values (260, 'Asphalt Paving');
insert into app_category (id, name) values (261, 'Granite Surfaces');
insert into app_category (id, name) values (262, 'Soft Flooring and Base');
insert into app_category (id, name) values (263, 'Glass & Glazing');
insert into app_category (id, name) values (264, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (265, 'Casework');
insert into app_category (id, name) values (266, 'Electrical');
insert into app_category (id, name) values (267, 'Sitework & Site Utilities');
insert into app_category (id, name) values (268, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (269, 'Waterproofing & Caulking');
insert into app_category (id, name) values (270, 'Drilled Shafts');
insert into app_category (id, name) values (271, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (272, 'EIFS');
insert into app_category (id, name) values (273, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (274, 'Sitework & Site Utilities');
insert into app_category (id, name) values (275, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (276, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (277, 'Exterior Signage');
insert into app_category (id, name) values (278, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (279, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (280, 'Elevator');
insert into app_category (id, name) values (281, 'Soft Flooring and Base');
insert into app_category (id, name) values (282, 'Ornamental Railings');
insert into app_category (id, name) values (283, 'Framing (Steel)');
insert into app_category (id, name) values (284, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (285, 'Glass & Glazing');
insert into app_category (id, name) values (286, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (287, 'Waterproofing & Caulking');
insert into app_category (id, name) values (288, 'Exterior Signage');
insert into app_category (id, name) values (289, 'Soft Flooring and Base');
insert into app_category (id, name) values (290, 'Casework');
insert into app_category (id, name) values (291, 'Drilled Shafts');
insert into app_category (id, name) values (292, 'Curb & Gutter');
insert into app_category (id, name) values (293, 'Masonry & Precast');
insert into app_category (id, name) values (294, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (295, 'Casework');
insert into app_category (id, name) values (296, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (297, 'Marlite Panels (FED)');
insert into app_category (id, name) values (298, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (299, 'Sitework & Site Utilities');
insert into app_category (id, name) values (300, 'Roofing (Metal)');
insert into app_category (id, name) values (301, 'Elevator');
insert into app_category (id, name) values (302, 'Drilled Shafts');
insert into app_category (id, name) values (303, 'Framing (Steel)');
insert into app_category (id, name) values (304, 'EIFS');
insert into app_category (id, name) values (305, 'Landscaping & Irrigation');
insert into app_category (id, name) values (306, 'Termite Control');
insert into app_category (id, name) values (307, 'Drilled Shafts');
insert into app_category (id, name) values (308, 'Hard Tile & Stone');
insert into app_category (id, name) values (309, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (310, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (311, 'Exterior Signage');
insert into app_category (id, name) values (312, 'Roofing (Asphalt)');
insert into app_category (id, name) values (313, 'Framing (Wood)');
insert into app_category (id, name) values (314, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (315, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (316, 'Electrical');
insert into app_category (id, name) values (317, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (318, 'EIFS');
insert into app_category (id, name) values (319, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (320, 'Framing (Steel)');
insert into app_category (id, name) values (321, 'Wall Protection');
insert into app_category (id, name) values (322, 'Framing (Steel)');
insert into app_category (id, name) values (323, 'Ornamental Railings');
insert into app_category (id, name) values (324, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (325, 'Epoxy Flooring');
insert into app_category (id, name) values (326, 'Epoxy Flooring');
insert into app_category (id, name) values (327, 'Framing (Wood)');
insert into app_category (id, name) values (328, 'Masonry');
insert into app_category (id, name) values (329, 'Waterproofing & Caulking');
insert into app_category (id, name) values (330, 'Casework');
insert into app_category (id, name) values (331, 'Soft Flooring and Base');
insert into app_category (id, name) values (332, 'Marlite Panels (FED)');
insert into app_category (id, name) values (333, 'Overhead Doors');
insert into app_category (id, name) values (334, 'Wall Protection');
insert into app_category (id, name) values (335, 'Site Furnishings');
insert into app_category (id, name) values (336, 'Wall Protection');
insert into app_category (id, name) values (337, 'Framing (Steel)');
insert into app_category (id, name) values (338, 'Fire Protection');
insert into app_category (id, name) values (339, 'RF Shielding');
insert into app_category (id, name) values (340, 'Epoxy Flooring');
insert into app_category (id, name) values (341, 'Electrical');
insert into app_category (id, name) values (342, 'EIFS');
insert into app_category (id, name) values (343, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (344, 'Soft Flooring and Base');
insert into app_category (id, name) values (345, 'Masonry');
insert into app_category (id, name) values (346, 'Epoxy Flooring');
insert into app_category (id, name) values (347, 'Wall Protection');
insert into app_category (id, name) values (348, 'Wall Protection');
insert into app_category (id, name) values (349, 'Wall Protection');
insert into app_category (id, name) values (350, 'Epoxy Flooring');
insert into app_category (id, name) values (351, 'Casework');
insert into app_category (id, name) values (352, 'Prefabricated Aluminum Metal Canopies');
insert into app_category (id, name) values (353, 'Epoxy Flooring');
insert into app_category (id, name) values (354, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (355, 'Termite Control');
insert into app_category (id, name) values (356, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (357, 'Marlite Panels (FED)');
insert into app_category (id, name) values (358, 'Fire Protection');
insert into app_category (id, name) values (359, 'Waterproofing & Caulking');
insert into app_category (id, name) values (360, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (361, 'Elevator');
insert into app_category (id, name) values (362, 'Soft Flooring and Base');
insert into app_category (id, name) values (363, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (364, 'Sitework & Site Utilities');
insert into app_category (id, name) values (365, 'Waterproofing & Caulking');
insert into app_category (id, name) values (366, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (367, 'Roofing (Metal)');
insert into app_category (id, name) values (368, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (369, 'Ornamental Railings');
insert into app_category (id, name) values (370, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (371, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (372, 'Elevator');
insert into app_category (id, name) values (373, 'Glass & Glazing');
insert into app_category (id, name) values (374, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (375, 'Roofing (Asphalt)');
insert into app_category (id, name) values (376, 'Exterior Signage');
insert into app_category (id, name) values (377, 'Elevator');
insert into app_category (id, name) values (378, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (379, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (380, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (381, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (382, 'EIFS');
insert into app_category (id, name) values (383, 'Masonry');
insert into app_category (id, name) values (384, 'Sitework & Site Utilities');
insert into app_category (id, name) values (385, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (386, 'Asphalt Paving');
insert into app_category (id, name) values (387, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (388, 'Roofing (Asphalt)');
insert into app_category (id, name) values (389, 'Waterproofing & Caulking');
insert into app_category (id, name) values (390, 'Masonry & Precast');
insert into app_category (id, name) values (391, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (392, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (393, 'Roofing (Metal)');
insert into app_category (id, name) values (394, 'Ornamental Railings');
insert into app_category (id, name) values (395, 'Curb & Gutter');
insert into app_category (id, name) values (396, 'Fire Protection');
insert into app_category (id, name) values (397, 'Masonry & Precast');
insert into app_category (id, name) values (398, 'Framing (Steel)');
insert into app_category (id, name) values (399, 'Sitework & Site Utilities');
insert into app_category (id, name) values (400, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (401, 'Masonry & Precast');
insert into app_category (id, name) values (402, 'Termite Control');
insert into app_category (id, name) values (403, 'Glass & Glazing');
insert into app_category (id, name) values (404, 'Roofing (Metal)');
insert into app_category (id, name) values (405, 'HVAC');
insert into app_category (id, name) values (406, 'Site Furnishings');
insert into app_category (id, name) values (407, 'EIFS');
insert into app_category (id, name) values (408, 'Soft Flooring and Base');
insert into app_category (id, name) values (409, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (410, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (411, 'EIFS');
insert into app_category (id, name) values (412, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (413, 'Framing (Wood)');
insert into app_category (id, name) values (414, 'Drilled Shafts');
insert into app_category (id, name) values (415, 'Exterior Signage');
insert into app_category (id, name) values (416, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (417, 'Wall Protection');
insert into app_category (id, name) values (418, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (419, 'Wall Protection');
insert into app_category (id, name) values (420, 'Ornamental Railings');
insert into app_category (id, name) values (421, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (422, 'Marlite Panels (FED)');
insert into app_category (id, name) values (423, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (424, 'Landscaping & Irrigation');
insert into app_category (id, name) values (425, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (426, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (427, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (428, 'Sitework & Site Utilities');
insert into app_category (id, name) values (429, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (430, 'Fire Protection');
insert into app_category (id, name) values (431, 'Termite Control');
insert into app_category (id, name) values (432, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (433, 'Overhead Doors');
insert into app_category (id, name) values (434, 'HVAC');
insert into app_category (id, name) values (435, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (436, 'Masonry');
insert into app_category (id, name) values (437, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (438, 'Wall Protection');
insert into app_category (id, name) values (439, 'Curb & Gutter');
insert into app_category (id, name) values (440, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (441, 'Glass & Glazing');
insert into app_category (id, name) values (442, 'Marlite Panels (FED)');
insert into app_category (id, name) values (443, 'Drilled Shafts');
insert into app_category (id, name) values (444, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (445, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (446, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (447, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (448, 'Termite Control');
insert into app_category (id, name) values (449, 'RF Shielding');
insert into app_category (id, name) values (450, 'Fire Protection');
insert into app_category (id, name) values (451, 'Electrical');
insert into app_category (id, name) values (452, 'Epoxy Flooring');
insert into app_category (id, name) values (453, 'Wall Protection');
insert into app_category (id, name) values (454, 'Fire Protection');
insert into app_category (id, name) values (455, 'Marlite Panels (FED)');
insert into app_category (id, name) values (456, 'Soft Flooring and Base');
insert into app_category (id, name) values (457, 'Sitework & Site Utilities');
insert into app_category (id, name) values (458, 'Overhead Doors');
insert into app_category (id, name) values (459, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (460, 'Drilled Shafts');
insert into app_category (id, name) values (461, 'Roofing (Metal)');
insert into app_category (id, name) values (462, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (463, 'Fire Sprinkler System');
insert into app_category (id, name) values (464, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (465, 'RF Shielding');
insert into app_category (id, name) values (466, 'Granite Surfaces');
insert into app_category (id, name) values (467, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (468, 'Waterproofing & Caulking');
insert into app_category (id, name) values (469, 'Landscaping & Irrigation');
insert into app_category (id, name) values (470, 'Ornamental Railings');
insert into app_category (id, name) values (471, 'Fire Protection');
insert into app_category (id, name) values (472, 'Hard Tile & Stone');
insert into app_category (id, name) values (473, 'Fire Sprinkler System');
insert into app_category (id, name) values (474, 'Curb & Gutter');
insert into app_category (id, name) values (475, 'Fire Protection');
insert into app_category (id, name) values (476, 'Landscaping & Irrigation');
insert into app_category (id, name) values (477, 'Casework');
insert into app_category (id, name) values (478, 'Fire Protection');
insert into app_category (id, name) values (479, 'Roofing (Metal)');
insert into app_category (id, name) values (480, 'Landscaping & Irrigation');
insert into app_category (id, name) values (481, 'Wall Protection');
insert into app_category (id, name) values (482, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (483, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (484, 'Asphalt Paving');
insert into app_category (id, name) values (485, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (486, 'Marlite Panels (FED)');
insert into app_category (id, name) values (487, 'Termite Control');
insert into app_category (id, name) values (488, 'Framing (Wood)');
insert into app_category (id, name) values (489, 'Electrical');
insert into app_category (id, name) values (490, 'Overhead Doors');
insert into app_category (id, name) values (491, 'Masonry');
insert into app_category (id, name) values (492, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (493, 'Sitework & Site Utilities');
insert into app_category (id, name) values (494, 'Soft Flooring and Base');
insert into app_category (id, name) values (495, 'Casework');
insert into app_category (id, name) values (496, 'Exterior Signage');
insert into app_category (id, name) values (497, 'Granite Surfaces');
insert into app_category (id, name) values (498, 'Roofing (Metal)');
insert into app_category (id, name) values (499, 'Masonry & Precast');
insert into app_category (id, name) values (500, 'Soft Flooring and Base');
insert into app_category (id, name) values (501, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (502, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (503, 'EIFS');
insert into app_category (id, name) values (504, 'Masonry & Precast');
insert into app_category (id, name) values (505, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (506, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (507, 'Asphalt Paving');
insert into app_category (id, name) values (508, 'Framing (Wood)');
insert into app_category (id, name) values (509, 'Sitework & Site Utilities');
insert into app_category (id, name) values (510, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (511, 'Landscaping & Irrigation');
insert into app_category (id, name) values (512, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (513, 'Fire Protection');
insert into app_category (id, name) values (514, 'Casework');
insert into app_category (id, name) values (515, 'Framing (Steel)');
insert into app_category (id, name) values (516, 'Epoxy Flooring');
insert into app_category (id, name) values (517, 'Electrical');
insert into app_category (id, name) values (518, 'Overhead Doors');
insert into app_category (id, name) values (519, 'Fire Sprinkler System');
insert into app_category (id, name) values (520, 'Fire Sprinkler System');
insert into app_category (id, name) values (521, 'Electrical');
insert into app_category (id, name) values (522, 'Fire Sprinkler System');
insert into app_category (id, name) values (523, 'RF Shielding');
insert into app_category (id, name) values (524, 'Sitework & Site Utilities');
insert into app_category (id, name) values (525, 'Marlite Panels (FED)');
insert into app_category (id, name) values (526, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (527, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (528, 'Fire Protection');
insert into app_category (id, name) values (529, 'Curb & Gutter');
insert into app_category (id, name) values (530, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (531, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (532, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (533, 'RF Shielding');
insert into app_category (id, name) values (534, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (535, 'HVAC');
insert into app_category (id, name) values (536, 'Roofing (Metal)');
insert into app_category (id, name) values (537, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (538, 'Wall Protection');
insert into app_category (id, name) values (539, 'Soft Flooring and Base');
insert into app_category (id, name) values (540, 'Glass & Glazing');
insert into app_category (id, name) values (541, 'HVAC');
insert into app_category (id, name) values (542, 'Termite Control');
insert into app_category (id, name) values (543, 'Casework');
insert into app_category (id, name) values (544, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (545, 'Site Furnishings');
insert into app_category (id, name) values (546, 'Drilled Shafts');
insert into app_category (id, name) values (547, 'Overhead Doors');
insert into app_category (id, name) values (548, 'Roofing (Metal)');
insert into app_category (id, name) values (549, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (550, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (551, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (552, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (553, 'Curb & Gutter');
insert into app_category (id, name) values (554, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (555, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (556, 'Roofing (Asphalt)');
insert into app_category (id, name) values (557, 'Casework');
insert into app_category (id, name) values (558, 'EIFS');
insert into app_category (id, name) values (559, 'Waterproofing & Caulking');
insert into app_category (id, name) values (560, 'Fire Sprinkler System');
insert into app_category (id, name) values (561, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (562, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (563, 'Ornamental Railings');
insert into app_category (id, name) values (564, 'Ornamental Railings');
insert into app_category (id, name) values (565, 'Hard Tile & Stone');
insert into app_category (id, name) values (566, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (567, 'Asphalt Paving');
insert into app_category (id, name) values (568, 'Masonry & Precast');
insert into app_category (id, name) values (569, 'Framing (Steel)');
insert into app_category (id, name) values (570, 'Elevator');
insert into app_category (id, name) values (571, 'Termite Control');
insert into app_category (id, name) values (572, 'Framing (Wood)');
insert into app_category (id, name) values (573, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (574, 'Framing (Wood)');
insert into app_category (id, name) values (575, 'Marlite Panels (FED)');
insert into app_category (id, name) values (576, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (577, 'Overhead Doors');
insert into app_category (id, name) values (578, 'Framing (Wood)');
insert into app_category (id, name) values (579, 'Waterproofing & Caulking');
insert into app_category (id, name) values (580, 'Epoxy Flooring');
insert into app_category (id, name) values (581, 'Landscaping & Irrigation');
insert into app_category (id, name) values (582, 'Sitework & Site Utilities');
insert into app_category (id, name) values (583, 'Hard Tile & Stone');
insert into app_category (id, name) values (584, 'Masonry & Precast');
insert into app_category (id, name) values (585, 'Fire Protection');
insert into app_category (id, name) values (586, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (587, 'Masonry');
insert into app_category (id, name) values (588, 'Prefabricated Aluminum Metal Canopies');
insert into app_category (id, name) values (589, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (590, 'Masonry');
insert into app_category (id, name) values (591, 'Ornamental Railings');
insert into app_category (id, name) values (592, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (593, 'Curb & Gutter');
insert into app_category (id, name) values (594, 'Roofing (Asphalt)');
insert into app_category (id, name) values (595, 'Curb & Gutter');
insert into app_category (id, name) values (596, 'Hard Tile & Stone');
insert into app_category (id, name) values (597, 'Framing (Steel)');
insert into app_category (id, name) values (598, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (599, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (600, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (601, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (602, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (603, 'Overhead Doors');
insert into app_category (id, name) values (604, 'Site Furnishings');
insert into app_category (id, name) values (605, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (606, 'Waterproofing & Caulking');
insert into app_category (id, name) values (607, 'Roofing (Asphalt)');
insert into app_category (id, name) values (608, 'Asphalt Paving');
insert into app_category (id, name) values (609, 'RF Shielding');
insert into app_category (id, name) values (610, 'Marlite Panels (FED)');
insert into app_category (id, name) values (611, 'Framing (Steel)');
insert into app_category (id, name) values (612, 'Site Furnishings');
insert into app_category (id, name) values (613, 'EIFS');
insert into app_category (id, name) values (614, 'Sitework & Site Utilities');
insert into app_category (id, name) values (615, 'EIFS');
insert into app_category (id, name) values (616, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (617, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (618, 'Landscaping & Irrigation');
insert into app_category (id, name) values (619, 'Elevator');
insert into app_category (id, name) values (620, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (621, 'Framing (Wood)');
insert into app_category (id, name) values (622, 'RF Shielding');
insert into app_category (id, name) values (623, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (624, 'Framing (Steel)');
insert into app_category (id, name) values (625, 'RF Shielding');
insert into app_category (id, name) values (626, 'Roofing (Metal)');
insert into app_category (id, name) values (627, 'Drilled Shafts');
insert into app_category (id, name) values (628, 'Wall Protection');
insert into app_category (id, name) values (629, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (630, 'Fire Protection');
insert into app_category (id, name) values (631, 'Site Furnishings');
insert into app_category (id, name) values (632, 'Roofing (Metal)');
insert into app_category (id, name) values (633, 'Masonry');
insert into app_category (id, name) values (634, 'Waterproofing & Caulking');
insert into app_category (id, name) values (635, 'Framing (Steel)');
insert into app_category (id, name) values (636, 'Framing (Wood)');
insert into app_category (id, name) values (637, 'Masonry & Precast');
insert into app_category (id, name) values (638, 'Epoxy Flooring');
insert into app_category (id, name) values (639, 'Waterproofing & Caulking');
insert into app_category (id, name) values (640, 'Hard Tile & Stone');
insert into app_category (id, name) values (641, 'Exterior Signage');
insert into app_category (id, name) values (642, 'Fire Sprinkler System');
insert into app_category (id, name) values (643, 'Soft Flooring and Base');
insert into app_category (id, name) values (644, 'Fire Protection');
insert into app_category (id, name) values (645, 'Epoxy Flooring');
insert into app_category (id, name) values (646, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (647, 'Sitework & Site Utilities');
insert into app_category (id, name) values (648, 'Waterproofing & Caulking');
insert into app_category (id, name) values (649, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (650, 'HVAC');
insert into app_category (id, name) values (651, 'Ornamental Railings');
insert into app_category (id, name) values (652, 'Masonry');
insert into app_category (id, name) values (653, 'Soft Flooring and Base');
insert into app_category (id, name) values (654, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (655, 'Wall Protection');
insert into app_category (id, name) values (656, 'Exterior Signage');
insert into app_category (id, name) values (657, 'EIFS');
insert into app_category (id, name) values (658, 'Landscaping & Irrigation');
insert into app_category (id, name) values (659, 'Fire Sprinkler System');
insert into app_category (id, name) values (660, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (661, 'RF Shielding');
insert into app_category (id, name) values (662, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (663, 'Termite Control');
insert into app_category (id, name) values (664, 'Exterior Signage');
insert into app_category (id, name) values (665, 'Overhead Doors');
insert into app_category (id, name) values (666, 'Asphalt Paving');
insert into app_category (id, name) values (667, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (668, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (669, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (670, 'Casework');
insert into app_category (id, name) values (671, 'RF Shielding');
insert into app_category (id, name) values (672, 'RF Shielding');
insert into app_category (id, name) values (673, 'Casework');
insert into app_category (id, name) values (674, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (675, 'Ornamental Railings');
insert into app_category (id, name) values (676, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (677, 'Elevator');
insert into app_category (id, name) values (678, 'Masonry');
insert into app_category (id, name) values (679, 'RF Shielding');
insert into app_category (id, name) values (680, 'Electrical');
insert into app_category (id, name) values (681, 'Curb & Gutter');
insert into app_category (id, name) values (682, 'Hard Tile & Stone');
insert into app_category (id, name) values (683, 'Epoxy Flooring');
insert into app_category (id, name) values (684, 'Framing (Steel)');
insert into app_category (id, name) values (685, 'Fire Protection');
insert into app_category (id, name) values (686, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (687, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (688, 'Soft Flooring and Base');
insert into app_category (id, name) values (689, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (690, 'RF Shielding');
insert into app_category (id, name) values (691, 'Wall Protection');
insert into app_category (id, name) values (692, 'Roofing (Metal)');
insert into app_category (id, name) values (693, 'Marlite Panels (FED)');
insert into app_category (id, name) values (694, 'Soft Flooring and Base');
insert into app_category (id, name) values (695, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (696, 'Curb & Gutter');
insert into app_category (id, name) values (697, 'Prefabricated Aluminum Metal Canopies');
insert into app_category (id, name) values (698, 'Epoxy Flooring');
insert into app_category (id, name) values (699, 'Wall Protection');
insert into app_category (id, name) values (700, 'Sitework & Site Utilities');
insert into app_category (id, name) values (701, 'Fire Sprinkler System');
insert into app_category (id, name) values (702, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (703, 'Glass & Glazing');
insert into app_category (id, name) values (704, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (705, 'Granite Surfaces');
insert into app_category (id, name) values (706, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (707, 'Masonry & Precast');
insert into app_category (id, name) values (708, 'Exterior Signage');
insert into app_category (id, name) values (709, 'Overhead Doors');
insert into app_category (id, name) values (710, 'Ornamental Railings');
insert into app_category (id, name) values (711, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (712, 'Fire Protection');
insert into app_category (id, name) values (713, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (714, 'Fire Protection');
insert into app_category (id, name) values (715, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (716, 'Masonry');
insert into app_category (id, name) values (717, 'Exterior Signage');
insert into app_category (id, name) values (718, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (719, 'Fire Protection');
insert into app_category (id, name) values (720, 'Asphalt Paving');
insert into app_category (id, name) values (721, 'Prefabricated Aluminum Metal Canopies');
insert into app_category (id, name) values (722, 'Termite Control');
insert into app_category (id, name) values (723, 'Framing (Steel)');
insert into app_category (id, name) values (724, 'RF Shielding');
insert into app_category (id, name) values (725, 'Masonry & Precast');
insert into app_category (id, name) values (726, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (727, 'Exterior Signage');
insert into app_category (id, name) values (728, 'Glass & Glazing');
insert into app_category (id, name) values (729, 'RF Shielding');
insert into app_category (id, name) values (730, 'Ornamental Railings');
insert into app_category (id, name) values (731, 'Overhead Doors');
insert into app_category (id, name) values (732, 'Roofing (Metal)');
insert into app_category (id, name) values (733, 'Masonry');
insert into app_category (id, name) values (734, 'Prefabricated Aluminum Metal Canopies');
insert into app_category (id, name) values (735, 'Curb & Gutter');
insert into app_category (id, name) values (736, 'Waterproofing & Caulking');
insert into app_category (id, name) values (737, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (738, 'Roofing (Asphalt)');
insert into app_category (id, name) values (739, 'Masonry');
insert into app_category (id, name) values (740, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (741, 'Granite Surfaces');
insert into app_category (id, name) values (742, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (743, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (744, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (745, 'Prefabricated Aluminum Metal Canopies');
insert into app_category (id, name) values (746, 'Wall Protection');
insert into app_category (id, name) values (747, 'Curb & Gutter');
insert into app_category (id, name) values (748, 'Waterproofing & Caulking');
insert into app_category (id, name) values (749, 'Exterior Signage');
insert into app_category (id, name) values (750, 'Hard Tile & Stone');
insert into app_category (id, name) values (751, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (752, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (753, 'Framing (Wood)');
insert into app_category (id, name) values (754, 'Drilled Shafts');
insert into app_category (id, name) values (755, 'Elevator');
insert into app_category (id, name) values (756, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (757, 'Exterior Signage');
insert into app_category (id, name) values (758, 'Curb & Gutter');
insert into app_category (id, name) values (759, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (760, 'Wall Protection');
insert into app_category (id, name) values (761, 'Glass & Glazing');
insert into app_category (id, name) values (762, 'Framing (Steel)');
insert into app_category (id, name) values (763, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (764, 'Overhead Doors');
insert into app_category (id, name) values (765, 'Casework');
insert into app_category (id, name) values (766, 'Marlite Panels (FED)');
insert into app_category (id, name) values (767, 'Glass & Glazing');
insert into app_category (id, name) values (768, 'Waterproofing & Caulking');
insert into app_category (id, name) values (769, 'Epoxy Flooring');
insert into app_category (id, name) values (770, 'Masonry & Precast');
insert into app_category (id, name) values (771, 'Casework');
insert into app_category (id, name) values (772, 'Electrical');
insert into app_category (id, name) values (773, 'Site Furnishings');
insert into app_category (id, name) values (774, 'Curb & Gutter');
insert into app_category (id, name) values (775, 'Wall Protection');
insert into app_category (id, name) values (776, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (777, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (778, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (779, 'Casework');
insert into app_category (id, name) values (780, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (781, 'Soft Flooring and Base');
insert into app_category (id, name) values (782, 'Sitework & Site Utilities');
insert into app_category (id, name) values (783, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (784, 'Masonry & Precast');
insert into app_category (id, name) values (785, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (786, 'Granite Surfaces');
insert into app_category (id, name) values (787, 'Granite Surfaces');
insert into app_category (id, name) values (788, 'Exterior Signage');
insert into app_category (id, name) values (789, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (790, 'Ornamental Railings');
insert into app_category (id, name) values (791, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (792, 'Epoxy Flooring');
insert into app_category (id, name) values (793, 'Fire Protection');
insert into app_category (id, name) values (794, 'Asphalt Paving');
insert into app_category (id, name) values (795, 'EIFS');
insert into app_category (id, name) values (796, 'HVAC');
insert into app_category (id, name) values (797, 'Landscaping & Irrigation');
insert into app_category (id, name) values (798, 'Electrical');
insert into app_category (id, name) values (799, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (800, 'Electrical');
insert into app_category (id, name) values (801, 'Masonry & Precast');
insert into app_category (id, name) values (802, 'EIFS');
insert into app_category (id, name) values (803, 'HVAC');
insert into app_category (id, name) values (804, 'RF Shielding');
insert into app_category (id, name) values (805, 'Framing (Steel)');
insert into app_category (id, name) values (806, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (807, 'HVAC');
insert into app_category (id, name) values (808, 'Curb & Gutter');
insert into app_category (id, name) values (809, 'Electrical');
insert into app_category (id, name) values (810, 'Drilled Shafts');
insert into app_category (id, name) values (811, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (812, 'EIFS');
insert into app_category (id, name) values (813, 'Framing (Steel)');
insert into app_category (id, name) values (814, 'Hard Tile & Stone');
insert into app_category (id, name) values (815, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (816, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (817, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (818, 'Sitework & Site Utilities');
insert into app_category (id, name) values (819, 'RF Shielding');
insert into app_category (id, name) values (820, 'Electrical');
insert into app_category (id, name) values (821, 'Ornamental Railings');
insert into app_category (id, name) values (822, 'Electrical');
insert into app_category (id, name) values (823, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (824, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (825, 'Roofing (Metal)');
insert into app_category (id, name) values (826, 'Drilled Shafts');
insert into app_category (id, name) values (827, 'Hard Tile & Stone');
insert into app_category (id, name) values (828, 'Ornamental Railings');
insert into app_category (id, name) values (829, 'Masonry & Precast');
insert into app_category (id, name) values (830, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (831, 'RF Shielding');
insert into app_category (id, name) values (832, 'Drilled Shafts');
insert into app_category (id, name) values (833, 'Drywall & Acoustical (FED)');
insert into app_category (id, name) values (834, 'Granite Surfaces');
insert into app_category (id, name) values (835, 'Sitework & Site Utilities');
insert into app_category (id, name) values (836, 'Construction Clean and Final Clean');
insert into app_category (id, name) values (837, 'Epoxy Flooring');
insert into app_category (id, name) values (838, 'Drilled Shafts');
insert into app_category (id, name) values (839, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (840, 'Framing (Steel)');
insert into app_category (id, name) values (841, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (842, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (843, 'Drilled Shafts');
insert into app_category (id, name) values (844, 'Prefabricated Aluminum Metal Canopies');
insert into app_category (id, name) values (845, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (846, 'Landscaping & Irrigation');
insert into app_category (id, name) values (847, 'Electrical');
insert into app_category (id, name) values (848, 'Waterproofing & Caulking');
insert into app_category (id, name) values (849, 'Casework');
insert into app_category (id, name) values (850, 'Waterproofing & Caulking');
insert into app_category (id, name) values (851, 'EIFS');
insert into app_category (id, name) values (852, 'Exterior Signage');
insert into app_category (id, name) values (853, 'Framing (Wood)');
insert into app_category (id, name) values (854, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (855, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (856, 'Waterproofing & Caulking');
insert into app_category (id, name) values (857, 'Fire Protection');
insert into app_category (id, name) values (858, 'Site Furnishings');
insert into app_category (id, name) values (859, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (860, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (861, 'Masonry & Precast');
insert into app_category (id, name) values (862, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (863, 'Waterproofing & Caulking');
insert into app_category (id, name) values (864, 'Granite Surfaces');
insert into app_category (id, name) values (865, 'Sitework & Site Utilities');
insert into app_category (id, name) values (866, 'Roofing (Asphalt)');
insert into app_category (id, name) values (867, 'Exterior Signage');
insert into app_category (id, name) values (868, 'Waterproofing & Caulking');
insert into app_category (id, name) values (869, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (870, 'Masonry');
insert into app_category (id, name) values (871, 'Masonry');
insert into app_category (id, name) values (872, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (873, 'Wall Protection');
insert into app_category (id, name) values (874, 'Framing (Wood)');
insert into app_category (id, name) values (875, 'Temp Fencing, Decorative Fencing and Gates');
insert into app_category (id, name) values (876, 'Casework');
insert into app_category (id, name) values (877, 'Overhead Doors');
insert into app_category (id, name) values (878, 'Site Furnishings');
insert into app_category (id, name) values (879, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (880, 'Glass & Glazing');
insert into app_category (id, name) values (881, 'Marlite Panels (FED)');
insert into app_category (id, name) values (882, 'Roofing (Asphalt)');
insert into app_category (id, name) values (883, 'Fire Sprinkler System');
insert into app_category (id, name) values (884, 'Marlite Panels (FED)');
insert into app_category (id, name) values (885, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (886, 'Casework');
insert into app_category (id, name) values (887, 'Site Furnishings');
insert into app_category (id, name) values (888, 'Granite Surfaces');
insert into app_category (id, name) values (889, 'EIFS');
insert into app_category (id, name) values (890, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (891, 'Electrical');
insert into app_category (id, name) values (892, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (893, 'Curb & Gutter');
insert into app_category (id, name) values (894, 'Soft Flooring and Base');
insert into app_category (id, name) values (895, 'Elevator');
insert into app_category (id, name) values (896, 'Marlite Panels (FED)');
insert into app_category (id, name) values (897, 'Elevator');
insert into app_category (id, name) values (898, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (899, 'Site Furnishings');
insert into app_category (id, name) values (900, 'Curb & Gutter');
insert into app_category (id, name) values (901, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (902, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (903, 'Masonry');
insert into app_category (id, name) values (904, 'Granite Surfaces');
insert into app_category (id, name) values (905, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (906, 'Asphalt Paving');
insert into app_category (id, name) values (907, 'Wall Protection');
insert into app_category (id, name) values (908, 'Termite Control');
insert into app_category (id, name) values (909, 'Elevator');
insert into app_category (id, name) values (910, 'Wall Protection');
insert into app_category (id, name) values (911, 'Glass & Glazing');
insert into app_category (id, name) values (912, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (913, 'Site Furnishings');
insert into app_category (id, name) values (914, 'Landscaping & Irrigation');
insert into app_category (id, name) values (915, 'Overhead Doors');
insert into app_category (id, name) values (916, 'Prefabricated Aluminum Metal Canopies');
insert into app_category (id, name) values (917, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (918, 'Masonry');
insert into app_category (id, name) values (919, 'Granite Surfaces');
insert into app_category (id, name) values (920, 'Asphalt Paving');
insert into app_category (id, name) values (921, 'Masonry & Precast');
insert into app_category (id, name) values (922, 'Elevator');
insert into app_category (id, name) values (923, 'Masonry');
insert into app_category (id, name) values (924, 'Fire Protection');
insert into app_category (id, name) values (925, 'Asphalt Paving');
insert into app_category (id, name) values (926, 'Hard Tile & Stone');
insert into app_category (id, name) values (927, 'Framing (Steel)');
insert into app_category (id, name) values (928, 'Hard Tile & Stone');
insert into app_category (id, name) values (929, 'Roofing (Metal)');
insert into app_category (id, name) values (930, 'Hard Tile & Stone');
insert into app_category (id, name) values (931, 'Soft Flooring and Base');
insert into app_category (id, name) values (932, 'Fire Sprinkler System');
insert into app_category (id, name) values (933, 'Drywall & Acoustical (MOB)');
insert into app_category (id, name) values (934, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (935, 'Electrical');
insert into app_category (id, name) values (936, 'Elevator');
insert into app_category (id, name) values (937, 'Electrical');
insert into app_category (id, name) values (938, 'Fire Protection');
insert into app_category (id, name) values (939, 'Granite Surfaces');
insert into app_category (id, name) values (940, 'Masonry');
insert into app_category (id, name) values (941, 'Marlite Panels (FED)');
insert into app_category (id, name) values (942, 'Asphalt Paving');
insert into app_category (id, name) values (943, 'Retaining Wall and Brick Pavers');
insert into app_category (id, name) values (944, 'Masonry');
insert into app_category (id, name) values (945, 'Soft Flooring and Base');
insert into app_category (id, name) values (946, 'Plumbing & Medical Gas');
insert into app_category (id, name) values (947, 'Waterproofing & Caulking');
insert into app_category (id, name) values (948, 'Epoxy Flooring');
insert into app_category (id, name) values (949, 'Roofing (Asphalt)');
insert into app_category (id, name) values (950, 'Masonry & Precast');
insert into app_category (id, name) values (951, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (952, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (953, 'HVAC');
insert into app_category (id, name) values (954, 'Curb & Gutter');
insert into app_category (id, name) values (955, 'Marlite Panels (FED)');
insert into app_category (id, name) values (956, 'Waterproofing & Caulking');
insert into app_category (id, name) values (957, 'Masonry & Precast');
insert into app_category (id, name) values (958, 'Masonry & Precast');
insert into app_category (id, name) values (959, 'Drilled Shafts');
insert into app_category (id, name) values (960, 'Glass & Glazing');
insert into app_category (id, name) values (961, 'Framing (Steel)');
insert into app_category (id, name) values (962, 'Casework');
insert into app_category (id, name) values (963, 'Fire Sprinkler System');
insert into app_category (id, name) values (964, 'Framing (Steel)');
insert into app_category (id, name) values (965, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (966, 'Structural and Misc Steel (Fabrication)');
insert into app_category (id, name) values (967, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (968, 'Masonry & Precast');
insert into app_category (id, name) values (969, 'Electrical');
insert into app_category (id, name) values (970, 'Painting & Vinyl Wall Covering');
insert into app_category (id, name) values (971, 'Roofing (Metal)');
insert into app_category (id, name) values (972, 'Roofing (Metal)');
insert into app_category (id, name) values (973, 'Landscaping & Irrigation');
insert into app_category (id, name) values (974, 'Masonry & Precast');
insert into app_category (id, name) values (975, 'Termite Control');
insert into app_category (id, name) values (976, 'Marlite Panels (FED)');
insert into app_category (id, name) values (977, 'Fire Sprinkler System');
insert into app_category (id, name) values (978, 'Elevator');
insert into app_category (id, name) values (979, 'Structural & Misc Steel Erection');
insert into app_category (id, name) values (980, 'Waterproofing & Caulking');
insert into app_category (id, name) values (981, 'Electrical and Fire Alarm');
insert into app_category (id, name) values (982, 'Termite Control');
insert into app_category (id, name) values (983, 'Waterproofing & Caulking');
insert into app_category (id, name) values (984, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (985, 'Rebar & Wire Mesh Install');
insert into app_category (id, name) values (986, 'Ornamental Railings');
insert into app_category (id, name) values (987, 'Prefabricated Aluminum Metal Canopies');
insert into app_category (id, name) values (988, 'Drilled Shafts');
insert into app_category (id, name) values (989, 'Overhead Doors');
insert into app_category (id, name) values (990, 'Electrical');
insert into app_category (id, name) values (991, 'Curb & Gutter');
insert into app_category (id, name) values (992, 'Overhead Doors');
insert into app_category (id, name) values (993, 'EIFS');
insert into app_category (id, name) values (994, 'Doors, Frames & Hardware');
insert into app_category (id, name) values (995, 'Landscaping & Irrigation');
insert into app_category (id, name) values (996, 'Exterior Signage');
insert into app_category (id, name) values (997, 'Termite Control');
insert into app_category (id, name) values (998, 'Termite Control');
insert into app_category (id, name) values (999, 'Roofing (Asphalt)');
insert into app_category (id, name) values (1000, 'Glass & Glazing');
